In [1]:
import numpy as np

In [5]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
type(L[0])

int

In [7]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [8]:
type(L2[0])

str

In [ ]:
L3 = [True, '2', 3.0, 4] # python listeleri esnek olsuğundan farklı türdeki verileri içinde saklıyabiliyor
L3 

[True, '2', 3.0, 4]

In [13]:
for item in L3:
   print(type(item))


<class 'bool'>
<class 'str'>
<class 'float'>
<class 'int'>


In [17]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
x = np.array([3.14, 4, 2, 3]) # numpy eğer veriler farklıysa ve mümkün ise verileri değiştirir
print(x)
type(x[2]) # normalde listenin 3. elemanı olan 2. index e sahip 2 int olmasına rağmen float dönüyor

[3.14 4.   2.   3.  ]


numpy.float64

In [ ]:
np.array([1, 2, 3, 4], dtype=float) # kendimiz veri tipini belirleyebiliyoruz

array([1., 2., 3., 4.])

In [27]:
np.array([range(i, i +3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
np.zeros(10, dtype=int) # zeros 0 lardan oluşan dizi veya matris oluşturmamızı sağlar

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3, 5), dtype=int) # 1 lerden oluşan dizi veya matris oluşturmamızı sağlar

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full((3, 5), 3.14) # belirttiimiz elemandan oluşan bir matris oluşturmamızı sağlar

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
np.arange(0, 20, 2) # 0 dan başlayıp 20 ye kadar 20 dahil olmamak üzere 2 şer artan bir dizi oluşturmamızı sağlar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0, 1, 5) # 0-1 aralığında eşit aralıklı 5 değer içeren bir dizi oluştur

In [35]:
np.random.random((3, 3))  # 3x3 lük 0-1 aralığında düzgün dağılıma sahip bir matris oluşur

array([[0.39550494, 0.89620577, 0.56649365],
       [0.88227539, 0.81131199, 0.32747188],
       [0.23678376, 0.90349236, 0.53330129]])

In [37]:
np.random.normal(0, 1, (3, 3)) # ortalaması 0 ve sıtandart sapması 1 olan normal dağılıma sahip rastgele değerlerden oluşan 3x3 lük matris oluştur

array([[-0.02962225, -0.67112364, -1.34636815],
       [ 0.58253917, -1.34666815, -0.93393844],
       [ 0.56296496,  0.17421132,  0.42192034]])

In [ ]:
np.random.seed(42) # rastgelelik için sabit seed değeri bu sayede sürekli aynı değerlere sahip matris oluşur
matris = np.random.normal(loc=0, scale=1, size=(3, 3)) # parametreleri kullanarak yine istenen matris oluşturulabilir
matris

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

In [ ]:
np.random.randint(0, 10, (3, 3)) # [0, 10) aralığında rastgele tam sayılardan oluşan 3x3 boyutunda bir dizi oluştur

array([[4, 0, 9],
       [5, 8, 0],
       [9, 2, 6]], dtype=int32)

In [ ]:
np.eye(3) # 3x3 lük birim matris oluştur

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.empty(3)

array([1., 1., 1.])