## NumPy Array Attributes

In [1]:
import numpy as np
np.random.seed(0) # tekrarlanabilirlik için kullanılır

x1 = np.random.randint(10, size=6) # tek boyutlu dizi
x2 = np.random.randint(10, size=(3, 4)) # iki boyutlu dizi
x3 = np.random.randint(10, size=(3, 4, 5)) # üç boyutlu dizi

In [2]:
print(f"x3 ndim: {x3.ndim}")
print(f"x3 size: {x3.size}")
print(f"x3 shape: {x3.shape}")

x3 ndim: 3
x3 size: 60
x3 shape: (3, 4, 5)


In [3]:
print(f"dtype: {x3.dtype}")

dtype: int32


In [4]:
print(f"itemsize: {x3.itemsize} baytes")
print(f"nbytes: {x3.nbytes} bytes")

itemsize: 4 baytes
nbytes: 240 bytes


 ## Array Indexing: Accessing Single Elements

In [5]:
x1

array([5, 0, 3, 3, 7, 9], dtype=int32)

In [6]:
x1[0]

np.int32(5)

In [7]:
x1[4]

np.int32(7)

In [ ]:
x1[-1] # negatif indeksleme sondan birinci indeks 

np.int32(9)

In [11]:
x1[-2]

np.int32(7)

In [12]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [13]:
x2[0,0] # çok boyutlu bir dizide yani matriste konum belirtmek için virgül kullanılır

np.int32(3)

In [ ]:
x2[2, 0] # ilk satır ve sütun 0. indexten başlıyor

np.int32(1)

In [ ]:
x2[2, -1] # burada da negatif indexleme var sonuncu sütunu belirtiyoruz

np.int32(7)

In [16]:
x2[0, 0] = 12 # index belirttikten sonra elemanı değiştirebilirsin
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [18]:
x1[0] = 5.23232 # eğer tamsayı dizisine ondalık değer eklersen sadece tam kısmını alır
x1

array([5, 0, 3, 3, 7, 9], dtype=int32)

## Array Slicing: Accessing Subarrays

- herhangi bir elemana gitmek için : de kullanabilirsin 

In [19]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5] # ilk 5 eleman 

array([0, 1, 2, 3, 4])

In [ ]:
x[5:] # 5. index ten sonraki elemanların tamamı

array([5, 6, 7, 8, 9])

In [22]:
x[4:7]

array([4, 5, 6])

In [ ]:
x[::2] # aralıklı indexleme

array([0, 2, 4, 6, 8])

In [ ]:
x[1::2] # 1. indexten başlayıp 2 şer artan

array([1, 3, 5, 7, 9])

In [ ]:
x[1::3] # 1. indexten başlayıp 3 er aratan

array([1, 4, 7])

In [28]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [29]:
x[5::-2]

array([5, 3, 1])

###  Multidimensional subarrays

In [30]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [ ]:
x2[:2, :3] # 2 satır 3 sütun baştan başlayıp 2 satır aldığı için son satır gelmedi

array([[12,  5,  2],
       [ 7,  6,  8]], dtype=int32)

In [33]:
x2[:1, :2]

array([[12,  5]], dtype=int32)

In [35]:
x2[:3, :2]

array([[12,  5],
       [ 7,  6],
       [ 1,  6]], dtype=int32)

In [ ]:
x2[::-1, ::-1] 

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]], dtype=int32)

In [38]:
x2[:, 0] # x2 nin ilk sütunu

array([12,  7,  1], dtype=int32)

In [ ]:
x2[0] # x2 nin ilk satırı 

array([12,  5,  2,  4], dtype=int32)

### Subarrays as no-copy views

- büyük veri kopyası üzerinden erişilip değiştirilebilir
- ayrıca verinin türü çok önemli eğer numpy ise farklı pandas ise farklı eğer düz python dizisi ise farklı sonuçlra olur veriyi pandas ile okuduysan ona göre dilimleme yapmalısın

In [40]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [41]:
x2_sub = x2[:2, :2]
x2_sub

array([[12,  5],
       [ 7,  6]], dtype=int32)

In [42]:
x2_sub[0,0] = 99
x2_sub

array([[99,  5],
       [ 7,  6]], dtype=int32)

In [ ]:
print(x2) # kopyası üzenden işlem yapmamıza rağmen orjinal dizi değişmiş oldu

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


###  Reshaping of Arrays

In [45]:
grid = np.arange(1, 10).reshape((3, 3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
x = np.array([1, 2, 3])
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [51]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [53]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### Array Concatenation and Splitting

#### Concatenation of arrays

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])  # dizileri birleştirmek için kullanılır

array([1, 2, 3, 3, 2, 1])

In [55]:
z = [99, 99, 99]

np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [56]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([grid, grid], axis=1) # axis = 1 boyunca birleştir

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [62]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])

np.vstack([x, grid]) # diziyi dikey olarak birleştirir

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

## Splitting of arrays

In [66]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x,[3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [68]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [69]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [70]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
