In [2]:
import numpy as np

In [3]:
np.__version__

'2.2.6'

In [4]:
liste = [1, 2, 3, 4, 5] # python listesinde numpy dizisi oluşturma
dizi = np.array(liste)
print(dizi)
print(type(dizi))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
dizi2 = np.array([10, 20, 30, 40])
print(dizi2)                       # doğrudan oluşturma

[10 20 30 40]


In [6]:
# 3 boyutlu dizi

dizi_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
dizi_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [7]:
# sıfırlardan oluşan dizi oluşturma 
sifirlar = np.zeros(5)
sifirlar

array([0., 0., 0., 0., 0.])

In [8]:
# sıfırlardan oluşan matris oluşturma 2x3
sifir_matris = np.zeros((2, 3))
sifir_matris

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# birlerden oluşan dizi oluşturma 
birler = np.ones(4)
print(birler)

[1. 1. 1. 1.]


In [10]:
# 3x3'lük birlerden oluşan matris
bir_matris = np.ones((3, 3))
bir_matris

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# matrisi belirli bir elemanla doldurma 
# tüm elemanları 5 olan bir matris
dolu = np.full((3, 3), 5)
dolu

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [12]:
# boş dizi oluşturma 

bos = np.empty((3,3))
bos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
# arrange 
aralik = np.arange(0, 10, 2) 
aralik
# 0'dan başlayıp 10 a kadar 10 dahil değil 2 şer aracak şekilde bir dizi oluştur

array([0, 2, 4, 6, 8])

In [14]:
ters = np.arange(10, 0, -1)
ters

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [15]:
# linspace 
esit_aralik = np.linspace(0, 10, 5)
esit_aralik
# başlangıç ve bitiş sayısı arasını 5 eşit aralığa böler

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
# logspace : logaritmik ölçekte eşit aralık
log_aralik = np.logspace(0, 3, 4)
log_aralik

array([   1.,   10.,  100., 1000.])

In [17]:
# birim matris oluşturma 
birim = np.eye(3)
print(birim)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
# köşegen matris oluşturma 
kosegen = np.diag((3, 3,3,3,3))
kosegen

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

In [19]:
# 0-1 arasında rastgele sayı almamızı sağlar
rastgele = np.random.rand(3, 3)
rastgele

array([[0.5680872 , 0.93986158, 0.86277522],
       [0.15078408, 0.90675885, 0.49682803],
       [0.95608096, 0.49521403, 0.37328002]])

In [20]:
# bu da normal dağılıma sahip olacak şekilde sayıları seçer 
normal = np.random.randn(5)
normal

array([-1.21685288, -1.35397132, -0.20121055,  0.68509934,  0.73277176])

In [21]:
tam_sayilar = np.random.randint(1, 100, size=(3, 3))
tam_sayilar
# 1-100 arasında rastgele sayılar alır ve 3x3 matrise yerleştirir

array([[29, 84, 53],
       [ 9, 72, 24],
       [87, 73, 12]], dtype=int32)

In [22]:
# rastgeleliği sabitlemek için
np.random.seed(42)
sabit_rastgele = np.random.rand(3)
sabit_rastgele

array([0.37454012, 0.95071431, 0.73199394])

In [23]:
rng = np.random.default_rng(seed =42)
rng.random(3)
# yeni teknik 

array([0.77395605, 0.43887844, 0.85859792])

In [24]:
dizi = np.array([ [1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])
dizi

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
dizi.shape # boyut

(4, 4)

In [26]:
dizi.ndim # boyut sayısı

2

In [27]:
dizi.size # toplam karakter sayısı

16

In [28]:
dizi.dtype # veri tipi

dtype('int64')

In [29]:
dizi.itemsize # elemanların byte cinsinden boyutu

8

In [30]:
dizi.nbytes # toplam bellek kullanımı

128

In [31]:
# indexleme ve dilimleme işlemleri
dizi = np.array([10, 20, 30, 40, 50])
dizi[0]

np.int64(10)

In [32]:
dizi[-1] # sondan 1. eleman

np.int64(50)

In [33]:
dizi[1:4]

array([20, 30, 40])

In [34]:
dizi[:3]

array([10, 20, 30])

In [35]:
dizi[2:]

array([30, 40, 50])

In [36]:
dizi[::2]

array([10, 30, 50])

In [37]:
dizi[::-1]

array([50, 40, 30, 20, 10])

In [38]:
matris = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
matris

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
# Tek eleman [satır, sütun]
matris[0,0]

np.int64(1)

In [40]:
matris[1,2]

np.int64(7)

In [41]:
matris[-1,-1]

np.int64(12)

In [42]:
# satır seçme
matris[0]

array([1, 2, 3, 4])

In [43]:
matris[1, :]

array([5, 6, 7, 8])

In [44]:
# sütun seçme
matris[:, 0]

array([1, 5, 9])

In [45]:
matris[:,2]

array([ 3,  7, 11])

In [46]:
# alt matris seçme
matris[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [47]:
# her satrırdan ilk 2 eleman
matris[:, :2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [48]:
# Boolean indeksleme
dizi = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
dizi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
print(dizi > 5)

[False False False False False  True  True  True  True  True]


In [51]:
buyukler = dizi[dizi > 5]
buyukler

array([ 6,  7,  8,  9, 10])

In [52]:
# çift sayılar
cift = dizi[dizi %2 == 0]
cift

array([ 2,  4,  6,  8, 10])

In [53]:
# birden fazla kosul
sonuc = dizi[(dizi > 3) & (dizi < 8)]
sonuc

array([4, 5, 6, 7])

In [54]:
# Fancy indeksleme
dizi = np.array([10, 20, 30, 40, 50, 60])

In [55]:
indeksler = [0, 2, 4]
dizi[indeksler]

array([10, 30, 50])

In [57]:
matris = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

satirlar = [0, 2]
sutunlar = [1, 2]

In [58]:
matris[satirlar, :][:, sutunlar]

array([[2, 3],
       [8, 9]])

In [59]:
# Dizi şekillendirme
dizi = np.arange(12)
dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
matris = dizi.reshape(3, 4)
matris

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
matris2 = dizi.reshape(2, -1)
matris2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [62]:
dizi_3d = dizi.reshape(2, 3, 2)
dizi_3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [64]:
matris = np.array([[1, 2, 3], [4, 5, 6]])

duz = matris.flatten()
duz2 = matris.ravel()
duz

array([1, 2, 3, 4, 5, 6])

In [65]:
duz2

array([1, 2, 3, 4, 5, 6])

In [66]:
matris = np.array([[1, 2, 3], [4, 5, 6]])
matris.shape

(2, 3)

In [67]:
matris.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [69]:
np.transpose(matris)
 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [70]:
dizi1 = np.array([1, 2, 3])
dizi2 = np.array([4, 5, 6])

birlestirme = np.concatenate([dizi1, dizi2])
birlestirme

array([1, 2, 3, 4, 5, 6])

In [71]:
matris = np.array([[1, 2], [3, 4]])
matris2 = np.array([[5, 6], [7, 8]])
dikey = np.vstack([matris, matris2])
dikey

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [72]:
yatay = np.hstack([matris, matris2])
yatay

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [73]:
dizi = np.arange(12)

In [74]:
# 3 esit parçaya bölme
parçalama = np.split(dizi, 3)
parçalama

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [75]:
# Belirli indekslerden bölme
parçalama2 = np.split(dizi, [3, 7])
parçalama2 

[array([0, 1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11])]

In [76]:
matris = np.arange(16).reshape(4, 4)
matris

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
ust, alt = np.vsplit(matris, 2)
print(ust)
print(alt)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [80]:
sag, sol = np.hsplit(matris, 2)
print(sag)
print(sol)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [81]:
# Matematiksel fonksiyonlar
dizi = np.array([0, np.pi/2, np.pi])
dizi

array([0.        , 1.57079633, 3.14159265])

In [82]:
# Trigonometrik
print(np.sin(dizi))
print(np.cos(dizi))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [83]:
# Logaritma
sayilar = np.array([1, 10, 100,1000])
print(np.log10(sayilar))
print(np.log(sayilar))
print(np.log2(sayilar))

[0. 1. 2. 3.]
[0.         2.30258509 4.60517019 6.90775528]
[0.         3.32192809 6.64385619 9.96578428]


In [85]:
# üstel
print(np.exp([1, 2, 3]))

[ 2.71828183  7.3890561  20.08553692]


In [86]:
# mutlak değer
print(np.abs([-1, -2, 3, -4]))

[1 2 3 4]


In [87]:
# Yuvarlama
kesirli = np.array([1.23, 2.67, 3.14, 4.89])
print(np.round(kesirli))

[1. 3. 3. 5.]


In [88]:
print(np.floor(kesirli))
print(np.ceil(kesirli))

[1. 2. 3. 4.]
[2. 3. 4. 5.]


In [89]:
# Matris işlemleri
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [90]:
# Matris çarpımı

C = np.dot(A, B)
print(C)

[[19 22]
 [43 50]]


In [91]:
C2 = A@B
C2

array([[19, 22],
       [43, 50]])

In [93]:
# Determinant
det = np.linalg.det(A)
print(det)

-2.0000000000000004


In [94]:
# Ters matris
A_ters = np.linalg.inv(A)
A_ters

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [95]:
# özdeğerler ve özvektörler

osdegerler, ozvektorler = np.linalg.eig(A)
print(osdegerler)
print(ozvektorler)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [98]:
# istatiksel fonksiyonlar

dizi = np.arange(1,11)
dizi

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# toplam
np.sum(dizi)

np.int64(55)

In [100]:
# ortalama
np.mean(dizi)

np.float64(5.5)

In [101]:
# medyan
np.median(dizi)

np.float64(5.5)

In [102]:
# standart sapma
np.std(dizi)

np.float64(2.8722813232690143)

In [ ]:
# varyans
np.var(dizi)

np.float64(8.25)

In [104]:
# minimum ve maksimum

print(np.min(dizi))
print(np.max(dizi))

1
10


In [105]:
# minimum ve maksimum indeksler
print(np.argmin(dizi))
print(np.argmax(dizi))

0
9


In [106]:
# kümülatif toplam
print(np.cumsum(dizi))

[ 1  3  6 10 15 21 28 36 45 55]


In [107]:
# kümülatif çarpım
print(np.cumprod(dizi))

[      1       2       6      24     120     720    5040   40320  362880
 3628800]


In [109]:
# çok boyutlu dizilerde istatistikler
matris = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matris

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
# tüm elemanların toplamı
np.sum(matris)

np.int64(45)

In [113]:
# satır bazında tüm elemanların toplamı
np.sum(matris, axis=1)

array([ 6, 15, 24])

In [114]:
# sütun bazında toplam
np.sum(matris, axis=0)

array([12, 15, 18])

In [115]:
# satır bazında ortalama
np.mean(matris, axis = 1)

array([2., 5., 8.])

In [116]:
# sütun bazında maksimum
np.max(matris, axis=0)

array([7, 8, 9])

In [117]:
dizi = np.array([1, 2, 3])
print(dizi + 5)

[6 7 8]


In [118]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])
print(a + b)

[[11 22 33]
 [14 25 36]]


In [119]:
c = np.array([[1], [2], [3]])
d = np.array([10, 20, 30, 40])

In [120]:
print(c + d)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [123]:
matris = np.ones([3, 4])
satir = np.array([1, 2, 3, 4])
print(matris + satir)

[[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]


In [124]:
a = np.array([[1], [2], [3]])
b = np.array([[1, 2, 3, 4]])
a * b

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [125]:
try:
    a = np.ones((3, 4))
    b = np.ones((3, ))
    print(a + b)
except ValueError as e:
    print(f"Hata {e}")

Hata operands could not be broadcast together with shapes (3,4) (3,) 


In [126]:
dizi = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])
unique = np.unique(dizi)
unique

array([1, 2, 3, 4, 5, 6, 9])

In [127]:
unique, counts = np.unique(dizi, return_counts=True)
print(unique)
print(counts)

[1 2 3 4 5 6 9]
[2 1 2 1 2 1 1]


In [128]:
sirali = np.sort(dizi)
sirali

array([1, 1, 2, 3, 3, 4, 5, 5, 6, 9])

In [ ]:
dizi1 = np.array([1, 2, 3, 4, 5])
dizi2 = dizi1
dizi2[0] = 100
print(dizi1) # orjinal değişti

[100   2   3   4   5]


In [ ]:
dizi1 = np.array([1, 2, 3, 4, 5])
dizi2 = dizi1.view()
dizi2[0] = 100
dizi1 # orjinal değişti

array([100,   2,   3,   4,   5])

In [ ]:
dizi1 = np.array([1, 2, 3, 4, 5])
dizi2 = dizi1.copy()
dizi2[0] = 100
dizi1 # orjinal değişmedi

array([1, 2, 3, 4, 5])

In [132]:
import time

def python_dongusu(n):
    sonuc = []
    for i in range(n):
        sonuc.append(i ** 2)
    return sonuc

In [137]:
def numpy_vetorize(n):
    return np.arange(n) ** 2

In [134]:
n = 1000000

In [135]:
start = time.time()
python_dongusu(n)
python_sure = time.time() - start

In [138]:
start = time.time()
numpy_vetorize(n)
numpy_sure = time.time() - start

In [139]:
start = time.time()
python_dongusu(n)
numpy_sure = time.time() -start

In [140]:
print(f"Python: {python_sure:.4f} saniye")
print(f"NumPy: {numpy_sure:.4f} saniye")
print(f"NumPy {python_sure/numpy_sure:.1f}x daha hızlı!")

Python: 0.1069 saniye
NumPy: 0.0868 saniye
NumPy 1.2x daha hızlı!


In [141]:
matris = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

satir_ort = np.apply_along_axis(np.mean, axis=1, arr=matris)
satir_ort

array([2., 5., 8.])

In [142]:
def osel_fonksiyon(x):
    if x < 5:
        return x ** 2
    else:
        return x + 10

In [143]:
vektorize_fonk = np.vectorize(osel_fonksiyon)
dizi = np.array([1, 3, 5, 7, 9])
vektorize_fonk(dizi)

array([ 1,  9, 15, 17, 19])

In [144]:
dizi = np.array([1, 2, -3, 4, -5, 6, -7, 8])

masked_dizi = np.ma.masked_where(dizi < 0, dizi)
masked_dizi

masked_array(data=[1, 2, --, 4, --, 6, --, 8],
             mask=[False, False,  True, False,  True, False,  True, False],
       fill_value=999999)

In [145]:
masked_dizi.mean()

np.float64(4.2)

In [146]:
dizi_nan = np.array([1, 2, np.nan, 4, np.nan, 6])
print(np.nanmean(dizi_nan))
print(np.nansum(dizi_nan))

3.25
13.0
